# Generated by Django 4.1.9 on 2023-10-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('rutCliente', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('motivoConsulta', models.TextField()),
            ],
        ),
    ]
